## PART I - Data Preprocessing

### Import Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

# # Input data files are available in the read-only "../input/" directory
# # For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# # You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# # You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
tf.__version__

'2.3.1'

### Read in Data and Look at Data

In [3]:
dataset = pd.read_csv('../input/churn-predictions-personal/Churn_Predictions.csv')

In [ ]:
dataset.head()

In [4]:
X = dataset.iloc[:, 3:-1].values #excluding surname and customer id
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding Categorical Data

#### Encoding Gender 

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### Encoding Geography variable

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') 
# 1 in [1] means the geography variable is in the 2nd column
#remainder=passthrough means non-specified columns will not be dropped and stay untransformed

X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting dataset into Training and Test Set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## PART II - Building ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## PART3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training Set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5498 - accuracy: 0.7854
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4728 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4401 - accuracy: 0.8076
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4270 - accuracy: 0.8148
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4219 - accuracy: 0.8171
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4181 - accuracy: 0.8209
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4150 - accuracy: 0.8213
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4117 - accuracy: 0.8235
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8253
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4058 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8612
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8610
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3380 - accuracy: 0.8624
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8634
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8611
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8620
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8602
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8626
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8636
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 

## PART4 - Making the Predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?


In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)

In [26]:
y_pred = (y_pred > 0.5)

In [28]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [30]:
print(cm)

[[1497   98]
 [ 183  222]]


In [31]:
accuracy_score(y_test, y_pred)

0.8595